config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
  	get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :movies do
    collection do
      get 'search'
    end
  	resources :reviews, only: [:new], controller: 'movies/reviews'
  end
  resources :reviews, except: [:new], controller: 'movies/reviews'
  root 'movies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
	searchkick
	belongs_to :user
	has_many :reviews, dependent: :destroy
	has_attached_file :image, styles: { medium: "400x600#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
#	base_url Rails.application.config.api_server_url
#	get		:all,		"/movies"
#	get 	:find,		"/movies/:id"
#	put 	:save,		"/movies/:id"
#	post 	:create,	"/movies"
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
	belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movies
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies/reviews_controller.rb
module Reviews

  require 'themoviedb'
  require 'yaml'

  class Movies::ReviewsController < MoviesController
    before_action :set_movie
    before_action :set_review, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!

    Tmdb::Api.key("b5eca1ae38bd3945a2564f64ff6595e0")

    # GET /reviews
    # GET /reviews.json
    def index
      @reviews = Review.all
    end

    # GET /reviews/1
    # GET /reviews/1.json
    def show    
    end

    # GET /reviews/new
    def new
      @review = Review.new
    end

    # GET /reviews/1/edit
    def edit
    end

    # POST /reviews
    # POST /reviews.json
    def create
      @review = Review.new(review_params)
      @review.user_id = current_user.id
      @review.movie_id = :movie_id

      respond_to do |format|
        if @review.save
          format.html { redirect_to @movie, notice: 'Review was successfully created.' }
          format.json { render :show, status: :created, location: review_path }
        else
          format.html { render :new }
          format.json { render json: @review.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /reviews/1
    # PATCH/PUT /reviews/1.json
    def update
      respond_to do |format|
        if @review.update(review_params)
          format.html { redirect_to movie_path(@review.movie_id), notice: 'Review was successfully updated.' }
          format.json { render :show, status: :ok, location: review_path }
        else
          format.html { render :edit }
          format.json { render json: @review.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /reviews/1
    # DELETE /reviews/1.json
    def destroy
      @review.destroy
      respond_to do |format|
        format.html { redirect_to :back, notice: 'Review was successfully deleted.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.

      def set_movie
        @movie = Tmdb::Movie.detail(params[:movie_id])
        @movie_id = @movie['id']
      end

      def set_review
        @review = Review.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def review_params
        params.require(:review).permit(:rating, :comment, :movie_id)
      end
  end
end

app/controllers/movies_controller.rb
require 'themoviedb'

class MoviesController < ApplicationController
	before_action :set_movie, only: [:show, :new, :create, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show, :search]
	# GET /movies
	# GET /movies.json

	Tmdb::Api.key("b5eca1ae38bd3945a2564f64ff6595e0")

	def index
		#@movies = Movie.all.order('title').paginate(page: params[:page], per_page: 4)
		if params[:filter] == "popular"
			@movies = Tmdb::Movie.popular
			@headline = "Most Popular"
		elsif params[:filter] == "toprated"
			@movies = Tmdb::Movie.top_rated
			@headline = "Top Rated"
		elsif params[:filter] == "nowplaying"
			@movies = Tmdb::Movie.now_playing
			@headline = "Playing Now"
		elsif params[:filter] == "upcoming"
			@movies = Tmdb::Movie.upcoming
			@headline = "Coming Soon"
		else
			@movies = Tmdb::Movie.popular
			@headline = "Most Popular"
		end

		if params[:order] == "title"
			@movies.sort! { |a,b| a.title <=> b.title }
			@subheadline = "by Title"
		elsif params[:order] == "release"
			@movies.sort! { |a,b| a.release_date <=> b.release_date }
			@subheadline = "by Release Date"
		elsif params[:order] == "genre"
			@movies.sort! { |a,b| a.genres <=> b.genres }
			@subheadline = "by Genre"
		else
			@movies.sort! { |a,b| a.title <=> b.title }
		end
	end

	def search
		if params[:search].present?
			@movies = Tmdb::Movie.find(params[:search])
		else
			@movies = Tmdb::Movie.popular
		end

		if params[:order] == "title"
			@movies.sort! { |a,b| a.title <=> b.title }
			@subheadline = "by Title"
		elsif params[:order] == "release"
			@movies.sort! { |a,b| a.release_date <=> b.release_date }
			@subheadline = "by Release Date"
		elsif params[:order] == "genre"
			@movies.sort! { |a,b| a.genres <=> b.genres }
			@subheadline = "by Genre"
		else
			@movies.sort! { |a,b| a.title <=> b.title }
		end
	end
	# GET /movies/1
	# GET /movies/1.json
	def show
		@reviews = Review.where(movie_id: @movie['id']).order("created_at DESC")
		if @reviews.blank?
			@avg_review = 0
		else
			@avg_review = @reviews.average(:rating).round(2)
		end
	end

	# GET /movies/new
	def new
		@movie = current_user.movies.build
	end

	# GET /movies/1/edit
	def edit
	end

	# POST /movies
	# POST /movies.json
	def create
		@movie = current_user.movies.build(movie_params)

		respond_to do |format|
			if @movie.save
				format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
				format.json { render :show, status: :created, location: @movie }
			else
				format.html { render :new }
				format.json { render json: @movie.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /movies/1
	# PATCH/PUT /movies/1.json
	def update
		respond_to do |format|
			if @movie.update(movie_params)
				format.html { redirect_to movies_url, notice: 'Movie was successfully updated.' }
				format.json { render :show, status: :ok, location: @movie }
			else
				format.html { render :edit }
				format.json { render json: @movie.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /movies/1
	# DELETE /movies/1.json
	def destroy
		@movie.destroy
		respond_to do |format|
			format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_movie
			@movie = Tmdb::Movie.detail(params[:id])
			@movie_id = @movie['id']
			@movie_poster = "https://image.tmdb.org/t/p/w185/#{@movie['poster_path']}"
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def movie_params
			params.require(:movie).permit(:title, :release_date, :genre, :rating, :image)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_footer.html.erb
<footer class="full fur-bg darkgray-bg white-txt pad-20-0">
	<div class="container">
		<h3>Contact</h3>
		<p>
			<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
			<a class="white-txt" href="mailto:rsmith@finixcreative.com">
				rsmith@finixcreative.com
			</a>
		</p>
		<p>
			<span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>
			<a class="white-txt" href="tel:617-417-2179">
				617-417-2179
			</a>			
		</p>
	</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default fixed full front">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">
				<%= image_tag "watchdoge-logo.png", alt: "WatchDoge Logo" %> WatchDoge <span class="sr-only">(current)</span>
			</a>
		</div>
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
						<span class="glyphicon glyphicon-filter" aria-hidden="true"></span> 
						Filters 
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li><%= link_to "Most Popular", movies_path({filter: "popular", order: params[:order]}) %></li>
						<li><%= link_to "Top Rated", movies_path({filter: "toprated", order: params[:order]}) %></li>
						<li><%= link_to "Playing Now", movies_path({filter: "nowplaying", order: params[:order]}) %></li>
						<li><%= link_to "Coming Soon", movies_path({filter: "upcoming", order: params[:order]}) %></li>
						<li role="separator" class="divider"></li>
						<li><%= link_to "Title", search: params[:search], filter: params[:filter], order: "title" %></li>
						<li><%= link_to "Release Date", search: params[:search], filter: params[:filter], order: "release" %></li>
						<li><%= link_to "Genre", search: params[:search], filter: params[:filter], order: "genre" %></li>
					</ul>
				</li>
			</ul>
			<%= form_tag search_movies_path, method: :get, class: "navbar-form navbar-left", role: "search" do %>
				<%= text_field_tag :search, params[:search], class: "form-control" %>
				<%= submit_tag "Search", name: nil, class: "btn btn-default" %>
			<% end %>
			<ul class="nav navbar-nav navbar-right">
				<% if !user_signed_in? %>
					<li>
						<a href="/users/sign_in">
							<span class="glyphicon glyphicon-user" aria-hidden="true"></span> 
							Log In
						</a>
					</li>
				<% else %>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
							<span class="glyphicon glyphicon-user" aria-hidden="true"></span> 
							<%= current_user.email %> 
							<span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "User info", edit_user_registration_path %></li>
							<li role="separator" class="divider"></li>
							<li><%= link_to "Log out", destroy_user_session_path %></li>
						</ul>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/_jumbotron.html.erb
<% if !user_signed_in? %>
	<div class="fur-bg orange-bg">
		<div class="jumbotron logo-bg">
			<div class="container">
				<h1>Welcome to WatchDoge</h1>
				<p>No account yet?</p>
				<p><%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %></p>
			</div>
		</div>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>WatchDoge</title>
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>
	<body class="fur-bg litegray-bg">
		<%= render 'layouts/header' %>
		<% flash.each do |name, message| %>
			<%= content_tag(:div, message, id: 'flash', class: 'alert pop-over') %>
		<% end %>
		<div class="pad-top-50">
			<%= yield %>		
		</div>
		<%= render 'layouts/footer' %>
		<script type="text/javascript">
			$(document).ready(function(){
				setTimeout(function(){
					$('#flash').fadeOut(1000, "linear", function(){
						$(this).hide();
					});
				}, 3000);
			})
		</script>
	</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie['id'], html: { multipart: true } do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :release_date %>
    <%= form.date_select :release_date %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_moviefeed.html.erb
<div class="row">
	<% @movies.each do |movie| %>
		<div class="col-md-3 col-sm-6 col-xs-6">
			<div class="thumbnail tile">
				<% if movie.poster_path %>
					<%= link_to (image_tag("https://image.tmdb.org/t/p/w185/#{movie.poster_path}")), movie_path(movie.id) %>
				<% else %>
					<%= link_to movie_path(movie.id) do %>
						<div class="missing-img">
							<p>Error loading image.</p>
						</div>
					<% end %>
				<% end %>
				<p class="title-link"><%= link_to (movie.title), movie_path(movie.id) %></p>
			</div>
		</div>
	<% end %>
</div>

app/views/movies/edit.html.erb
<div class="panel panel-default panel-body">
	<div class="container">
		<h1>Editing Movie</h1>
		<%= render 'form', movie: @movie %>
		<%= link_to 'Cancel', movie_path %>
	</div>
</div>

app/views/movies/index.html.erb
<%= render 'layouts/jumbotron' %>
<div class="container">
	<h1>
		<%= @headline %> 
		<small><%= @subheadline %></small>
	</h1>
	<%= render 'moviefeed' %>
</div>

app/views/movies/new.html.erb
<div class="panel panel-default panel-body">
	<div class="container">
		<h1>New Movie</h1>
		<%= render 'form', movie: @movie %>
		<%= link_to 'Cancel', movies_path %>
	</div>
</div>

app/views/movies/reviews/_form.html.erb
<%= form_for @review  do |f| %>
	<% if review.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:
			</h2>
			<ul>
				<% review.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="field">
		<%= f.label :rating %>
		<div id="star-rating" data-score= <%= review.rating %> ></div>
	</div>

	<div class="field">
		<%= f.label :comment %><br>
		<%= f.text_area :comment %>
	</div>

	<div class="field">
		<%= f.label :movie_id, "Movie ID" %><br>
		<%= f.text_area :movie_id %>
	</div>

	<div class="actions">
		<%= f.submit 'Complete', class: "btn btn-primary" %>
	</div>
<% end %>
<script>
	$('#star-rating').raty({
		path: '',
		scoreName: 'review[rating]',
		score: function(){
			return $(this).attr('data-score');
		}
	});
</script>

app/views/movies/reviews/edit.html.erb
<div class="panel panel-default panel-body">
	<div class="container">
		<h1>Editing Review</h1>
		<%= render 'form', review: @review %>
	</div>
</div>

app/views/movies/reviews/index.html.erb
<div class="panel panel-default panel-body">
	<div class="container">
		<h1>Reviews</h1>
		<table class="full">
			<thead>
				<tr>
					<th>Movie</th>
					<th>Rating</th>
					<th>Comment</th>
					<th>Date</th>
					<th colspan="3"></th>
				</tr>
			</thead>
			<tbody>
				<% @reviews.each do |review| %>
					<tr>
						<td><%= review.movie_id %></td>
						<td><div class="star-rating" data-score= <%= review.rating %> ></div></td>
						<td><%= review.comment %></td>
						<td><%= review.created_at %></td>						
						<td><%= link_to 'View', review, class: "btn btn-default" %></td>
						<td><%= link_to 'Edit', edit_review_path(review), class: "btn btn-default" %></td>
						<td><%= link_to 'Delete', review_path(review), class: "btn btn-default", method: :delete, data: { confirm: 'Are you sure?' } %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>
<script>
	$('.star-rating').raty({
		path: '',
		readOnly: true,
		score: function(){
			return $(this).attr('data-score');
		}
	});
</script>

app/views/movies/reviews/new.html.erb
<div class="panel panel-default panel-body">
	<div class="container">
		<h1>New Review</h1>
		<%= render 'form', review: @review %>
	</div>
</div>

app/views/movies/reviews/show.html.erb
<div class="panel panel-default panel-body">
	<div class="container">
		<p>
			<strong>Movie:</strong>
			<%= @review.movie_id %>
		</p>
		<p>
			<div class="star-rating" data-score= <%= @review.rating %> ></div>
		</p>
		<p>
			<strong>Comment:</strong>
			<%= @review.comment %>
		</p>
		<p>
			<strong>User:</strong>
			<%= @review.user.email %>
		</p>
		<% if @review.movie_id %>
			<%= link_to 'Movie', movie_path(@review.movie_id) %> | 
		<% end %>
		<%= link_to 'Reviews', reviews_path %>
	</div>
</div>
<script>
	$('.star-rating').raty({
		path: '',
		readOnly: true,
		score: function(){
			return $(this).attr('data-score');
		}
	});
</script>

app/views/movies/search.html.erb
<%= render 'layouts/jumbotron' %>
<div class="container">
	<h1>
		Search results for "<%= params[:search] %>" 
		<small><%= @subheadline %></small>
	</h1>
	<%= render 'moviefeed' %>
</div>

app/views/movies/show.html.erb
<div class="panel panel-default">
	<div class="container">
		<div class="panel-body">
			<p><%= link_to 'Back', :back %></p>
			<h1 class="movie-title">
				<%= @movie['title'] %>
			</h1>
			<div class="row">
				<div class="col-md-4">
					<div class="thumbnail col-md-12 col-sm-6">
						<% if @movie['poster_path'] %>
							<%= image_tag @movie_poster %>
						<% else %>
							<div class="missing-img">
								<p>Error loading image.</p>
							</div>
						<% end %>
					</div>
					<div class="table-responsive col-md-12 col-sm-6">
						<table class="table">
							<tbody>
								<tr>
									<td><strong>Title:</strong></td>
									<td><%= @movie['title'] %></td>
								</tr>
								<tr>
									<td><strong>Rating:</strong></td>
									<td>
										<div class="star-rating" data-score= <%= @avg_review %> ></div>
										<em><%= "#{@reviews.length} reviews" %></em>
									</td>
								</tr>
								<tr>
									<td><strong>Release date:</strong></td>
									<td><%= @movie['release_date'] %></td>
								</tr>
								<tr>
									<td><strong>Genre:</strong></td>
									<td>
										<p>
											<% @movie['genres'].each do |genre| %>
												<%= genre['name'] %><br>
											<% end %>
										</p>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
				<div class="col-md-8 col-sm-12">
					<h3 class="review-title">Reviews</h3>
					<p>
						<%= link_to 'New Review', new_movie_review_path(@movie_id, @review), class: "btn btn-primary" %>
					</p>
					<% if @reviews.blank? %>
						<p>No reviews yet.</p>
					<% else %>
					    <% @reviews.each do |review| %>
					    	<div class="reviews">
					    		<div class="star-rating" data-score=<%= review.rating %> ></div>
					    		<p><%= review.comment %></p>
					    		<% if user_signed_in? %>
						    		<p>
						    			<%= link_to 'Edit', edit_review_path(review.id) %> | 
						    			<%= link_to 'Delete', review_path(review.id), method: :delete, data: { confirm: 'Are you sure?' } %>
						    		</p>
						    	<% end %>
					    	</div>
					    <% end %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	$('.star-rating').raty({
		path: '',
		readOnly: true,
		score: function(){
			return $(this).attr('data-score');
		}
	});
</script>